Viết class và cài phương thức softmax


In [1]:
import torch
import torch.nn as nn

In [2]:
#Kieu du lieu cua torch la tensor
data =  torch.Tensor([1, 2, 3])
data

tensor([1., 2., 3.])

In [3]:
softmax_function = nn.Softmax(dim=0) #chieu = 0
output = softmax_function(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [4]:
class MySoftMax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_exp = torch.exp(x)
        total = x_exp.sum(0, keepdims = True)
        return x_exp/total

my_softmax = MySoftMax()
output = my_softmax(data)
output


tensor([0.0900, 0.2447, 0.6652])

In [5]:
data = torch.Tensor([1, 2, 30000000])
data

tensor([1.0000e+00, 2.0000e+00, 3.0000e+07])

In [6]:
#softmax binh thuong se bi NaN khi gap gia tri lon
output = my_softmax(data)
output 

tensor([0., 0., nan])

In [7]:
#Stable softmax
class StableSoftMax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdims=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition
    
data = torch.Tensor([1, 2, 3000000])
softmax_stable = StableSoftMax()
output = softmax_stable(data)
output
    

tensor([0., 0., 1.])

Exercise 2: OOP
MộtWard(phường)gồmcóname(string)vàdanhsáchcủamọingười trongWard.
Mộtngườipersoncóthểlàstudent,doctor,hoặcteacher.Mộtstudentgồmcóname,
yob(int)(nămsinh),vàgrade(string).Mộtteachergồmcóname,yob,vàsubject
(string).Mộtdoctorgồmcóname,yob,vàspecialist(string).Lưuýcầnsửdụnga
listđểchứadanhsáchcủamọingườitrongWard.

In [49]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

In [50]:
class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name = name, yob = yob)
        self.__grade = grade
    def describe(self):
        print(f"Student name: {self._name} - Student nam sinh: {self._yob} - Grade: {self.__grade}")
        

In [51]:
class Doctor(Person):
    def __init__(self, name, yob, specialist: str):
        super().__init__(name = name, yob = yob)
        self.__specialts = specialist

    def describe(self):
        print(f"Doc name: {self._name} - Student nam sinh: {self._yob} - Specialits: {self.__specialts}")

In [52]:
doctor1 = Doctor('Banh', 1992, 'Tim')
doctor2 = Doctor('Toan', 1994, 'Nguc')

doctor1.describe()
doctor2.describe()

Doc name: Banh - Student nam sinh: 1992 - Specialits: Tim
Doc name: Toan - Student nam sinh: 1994 - Specialits: Nguc


In [53]:
student1 = Student('Thai', 1999, 10)
student1.describe()

Student name: Thai - Student nam sinh: 1999 - Grade: 10


In [54]:
class Teacher(Person):
    def __init__(self, name, yob, subject:str):
        super().__init__(name = name, yob = yob)
        self.__subject = subject
    def describe(self):
        print(f"name: {self._name} - yob: {self._yob} - subject =  {self.__subject}")

In [55]:
teacher1 = Teacher('Lam', 1999, 'Toan')
teacher1.describe()

name: Lam - yob: 1999 - subject =  Toan


In [68]:
class Ward:
    def __init__(self, name):
        self._name = name
        self._list_people = list()

    def add_person(self, person: Person):
        self._list_people.append(person)

    def describe(self):
        print(f"Ten ward = {self._name}")
        for p in self._list_people:
            p.describe()
    
    def count_doctor(self):
        counter = 0
        for p in self._list_people:
            if isinstance(p, Doctor):
                counter += 1
        return counter
    def sort_age(self):
        self._list_people.sort(key=lambda x: x.get_yob(), reverse=True)

    def compute_average_yob(self):
        total = 0 
        counter = 0
        for p in self._list_people:
            if isinstance(p, Doctor):
                counter += 1
                total += p.get_yob()
        return total/counter
            

In [69]:
ward1 = Ward('Hai')

In [70]:
ward1.add_person(student1)
ward1.describe()

Ten ward = Hai
Student name: Thai - Student nam sinh: 1999 - Grade: 10


In [71]:
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.describe()

Ten ward = Hai
Student name: Thai - Student nam sinh: 1999 - Grade: 10
Doc name: Banh - Student nam sinh: 1992 - Specialits: Tim
Doc name: Toan - Student nam sinh: 1994 - Specialits: Nguc


In [72]:
ward1.count_doctor()

2

In [73]:
ward1.sort_age()
ward1.describe()

Ten ward = Hai
Student name: Thai - Student nam sinh: 1999 - Grade: 10
Doc name: Toan - Student nam sinh: 1994 - Specialits: Nguc
Doc name: Banh - Student nam sinh: 1992 - Specialits: Tim


In [75]:
ward1.compute_average_yob()


1993.0

Exercise 3: xây dựng class Stack

In [81]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    #tra ve True khi len = 0    
    def is_empty(self):
        return len(self.__stack) == 0
    
    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def pop(self):
        if self.is_empty():
            print("stack rong")
            return None
        else:
            return self.__stack.pop() #ham pop cua list tu dong lay phan tu cuoi
    
    def push(self, value):
        if self.is_full():
            print("stack day")
            return None
        else:
            self.__stack.append(value)
    
    def top(self):
        if self.is_empty():
            print("stack rong")
            return None
        else: 
            return self.__stack[-1]

In [80]:
stack1 = MyStack(3)
stack1.pop()
stack1.push(1)
stack1.push(3)
stack1.push(5)
stack1.pop()
stack1.top()

stack rong


3

Exercise 4: xây dựng class Queue


In [98]:
class MyQueue:
    def __init__(self, capacity: int):
        self.__capacity = capacity
        self.__queue = []
    
    def is_empty(self):
        return len(self.__queue) == 0
    
    def is_full(self):
        return len(self.__queue) == self.__capacity
    
    def dequeue(self):
        if self.is_empty():
            print("Queue rong")
            return None
        else:
            return self.__queue.pop(0)
    
    def enqueue(self, value):
        if self.is_full():
            self.__queue.pop(0)
            self.__queue.append(value)
        else:
            self.__queue.append(value)

    def front(self):
        if self.is_empty():
            print("queue rong")
            return None
        else:
            return self.__queue[0]
    
    def __str__(self):
        # Trả về một chuỗi văn bản (String) chứa cái mảng nội bộ
        return f"Trạng thái Queue hiện tại: {self.__queue}"

In [99]:
queue1 = MyQueue(3)
queue1.dequeue()




Queue rong


In [100]:
queue1.enqueue(1)
queue1.enqueue(2)
queue1.enqueue(3)
queue1.enqueue(4)
print(queue1)
queue1.front()

Trạng thái Queue hiện tại: [2, 3, 4]


2